# Generated by Django 5.2.3 on 2025-07-08 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeImage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='poses/')),
                ('anime_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poses', to='animeImage.animeimage')),
            ],
        ),
    ]
