# Generated by Django 5.2.3 on 2025-07-10 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeImage', '0002_poseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenplay_text', models.TextField()),
                ('generated_panel', models.ImageField(blank=True, null=True, upload_to='panels/')),
                ('anime_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='animeImage.animeimage')),
                ('selected_pose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animeImage.poseimage')),
            ],
        ),
    ]
