# Generated by Django 5.2.3 on 2025-07-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeImage', '0003_mangapage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MangaPage',
        ),
    ]
