# Generated by Django 5.2.3 on 2025-07-23 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animeImage', '0004_delete_mangapage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenplay_text', models.TextField()),
                ('generated_panel', models.ImageField(blank=True, null=True, upload_to='panels/')),
                ('anime_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='animeImage.animeimage')),
                ('selected_pose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animeImage.poseimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
