# Generated by Django 5.2.3 on 2025-07-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panelGeneration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangapage',
            name='selected_pose',
        ),
    ]
